"""Report generator orchestrator."""

import json
from pathlib import Path

from jinja2 import Template

from ..models.report import ReportConfig, ReportFormat
from ..models.results import InventoryResult
from . import charts, tables

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #f5f5f5; color: #333; }
        .container { max-width: 1200px; margin: 0 auto; }
        h1 { color: #1a1a1a; border-bottom: 3px solid #2196F3; padding-bottom: 10px; }
        h2 { color: #424242; margin-top: 40px; }
        .summary-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 20px 0; }
        .card { background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .card-value { font-size: 2em; font-weight: bold; color: #2196F3; }
        .card-label { color: #757575; font-size: 0.9em; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin: 16px 0; }
        th { background: #2196F3; color: white; padding: 12px; text-align: left; }
        td { padding: 10px 12px; border-bottom: 1px solid #eee; }
        tr:hover td { background: #f5f5f5; }
        .chart-container { background: white; border-radius: 8px; padding: 16px; margin: 16px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .methodology { background: white; border-radius: 8px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .footer { text-align: center; color: #757575; margin-top: 40px; padding: 20px; font-size: 0.85em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ title }}</h1>
        {% if year %}<p>Reporting Year: {{ year }}</p>{% endif %}

        <div class="summary-cards">
            <div class="card">
                <div class="card-value">{{ "%.1f"|format(total_tonnes) }}</div>
                <div class="card-label">Total tCO2e</div>
            </div>
            <div class="card">
                <div class="card-value">{{ "%.1f"|format(scope1_tonnes) }}</div>
                <div class="card-label">Scope 1 tCO2e</div>
            </div>
            <div class="card">
                <div class="card-value">{{ "%.1f"|format(scope2_tonnes) }}</div>
                <div class="card-label">Scope 2 tCO2e (Location)</div>
            </div>
            <div class="card">
                <div class="card-value">{{ "%.1f"|format(scope3_tonnes) }}</div>
                <div class="card-label">Scope 3 tCO2e</div>
            </div>
        </div>

        <h2>Scope Summary</h2>
        {{ scope_table }}

        {% if scope3_table %}
        <h2>Scope 3 Category Breakdown</h2>
        {{ scope3_table }}
        {% endif %}

        {% if gas_table %}
        <h2>Emissions by Gas</h2>
        {{ gas_table }}
        {% endif %}

        {% for chart_id, chart_json in charts %}
        <h2>{{ chart_id | replace('_', ' ') | title }}</h2>
        <div class="chart-container">
            <div id="{{ chart_id }}"></div>
            <script>Plotly.newPlot('{{ chart_id }}', {{ chart_json }});</script>
        </div>
        {% endfor %}

        {% if methodology %}
        <h2>Methodology</h2>
        <div class="methodology">
            <p>This report follows the <strong>GHG Protocol Corporate Accounting and Reporting Standard</strong>.</p>
            <ul>
                <li>Scope 1: Direct emissions from owned/controlled sources</li>
                <li>Scope 2: Indirect emissions from purchased electricity (dual reporting: location-based and market-based)</li>
                <li>Scope 3: All other indirect emissions in the value chain</li>
            </ul>
            <p>Global Warming Potentials: IPCC {{ gwp_assessment | upper }} (100-year)</p>
            <p>Report format: {{ report_format }}</p>
        </div>
        {% endif %}

        <div class="footer">
            Generated by GHG Calculator | GHG Protocol Corporate Standard
        </div>
    </div>
</body>
</html>"""


class ReportGenerator:
    """Generates HTML reports with tables and charts."""

    def generate(
        self,
        inventory: InventoryResult,
        config: ReportConfig,
        output_path: Path,
    ) -> Path:
        """Generate a full HTML report."""
        # Build tables
        scope_df = tables.scope_summary_table(inventory)
        scope3_df = tables.scope3_breakdown_table(inventory)
        gas_df = tables.gas_breakdown_table(inventory)

        # Build charts
        chart_data = []
        try:
            fig = charts.scope_donut_chart(inventory)
            chart_data.append(("scope_distribution", fig.to_json()))
        except Exception:
            pass

        try:
            fig = charts.category_stacked_bar(inventory)
            chart_data.append(("category_breakdown", fig.to_json()))
        except Exception:
            pass

        try:
            fig = charts.waterfall_chart(inventory)
            chart_data.append(("emission_buildup", fig.to_json()))
        except Exception:
            pass

        if inventory.scope3.total_co2e_tonnes > 0:
            try:
                fig = charts.scope3_treemap(inventory)
                chart_data.append(("scope3_treemap", fig.to_json()))
            except Exception:
                pass

        # Render
        template = Template(_HTML_TEMPLATE)
        html = template.render(
            title=config.title,
            year=inventory.year,
            total_tonnes=inventory.total_co2e_tonnes,
            scope1_tonnes=inventory.scope1.total_co2e_tonnes,
            scope2_tonnes=inventory.scope2_location.total_co2e_tonnes,
            scope3_tonnes=inventory.scope3.total_co2e_tonnes,
            scope_table=scope_df.to_html(index=False, classes="table"),
            scope3_table=scope3_df.to_html(index=False, classes="table") if inventory.scope3.total_co2e_tonnes > 0 else "",
            gas_table=gas_df.to_html(index=False, classes="table") if not gas_df.empty else "",
            charts=chart_data,
            methodology=config.include_methodology,
            gwp_assessment="ar5",
            report_format=config.format.value,
        )

        output_path = Path(output_path)
        output_path.write_text(html)
        return output_path
